"""drop knowledge_base.tags

Revision ID: a066de20b6f1
Revises: a3187e94b8f0
Create Date: 2026-07-30 02:49:07.502926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a066de20b6f1'
down_revision: Union[str, Sequence[str], None] = 'a3187e94b8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # KnowledgeBase.tags ORM 列已删除（标签功能整体下线），生产库仍残留该列，
    # 此处删除。IF EXISTS 防"列已被手动删过"导致整条迁移失败。
    op.execute("ALTER TABLE knowledge_base DROP COLUMN IF EXISTS tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
