"""drop document.tags and sync kb_dept_grant.id server_default

Revision ID: a3187e94b8f0
Revises: u12kggapsignal
Create Date: 2026-07-30 02:27:53.183240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3187e94b8f0'
down_revision: Union[str, Sequence[str], None] = 'u12kggapsignal'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # document.tags 在 ORM 模型层已移除（仅保留 knowledge_base.tags）；
    # 生产库仍残留该列，此处删除。IF EXISTS 防"列已被手动删过"导致整条迁移失败。
    op.execute("ALTER TABLE document DROP COLUMN IF EXISTS tags")
    # kb_dept_grant.id 的 server_default=gen_random_uuid() 由早期迁移 u11kbdeptgrant
    # 落到库里，但当前 ORM 模型只用 default=uuid.uuid4（Python 侧生成 id），二者不一致。
    # 移除库端冗余默认值，使 schema 与模型对齐。该 ALTER 幂等（无默认时 DROP DEFAULT 为 no-op）。
    op.alter_column('kb_dept_grant', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kb_dept_grant', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.add_column('document', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
